### ISSUE TITLE
macruby and minitest - nested specs don't seem to work.

### ISSUE THREAD

**Issue by petejkim** [minitest/minitest#189]
**code:**

``` ruby
class AIONumberToBooleanTransformer < NSValueTransformer
  def self.allowsReverseTransformation
    true
  end

  def transformedValue(value)
    !(value == 0)
  end

  def reverseTransformedValue(value)
    value == true ? 1 : 0
  end
end
```

``` ruby
require 'SpecHelper'
require 'AIONumberToBooleanTransformer'

describe AIONumberToBooleanTransformer do
  before do
    @transformer = AIONumberToBooleanTransformer.new
  end

  it 'is a subclass of NSValueTransformer' do
    @transformer.must_be_kind_of NSValueTransformer
  end

  describe 'transformation' do
    it 'converts 0 to false' do
      @transformer.transformedValue(0).must_equal false
    end

    it 'converts non-zero to true' do
      @transformer.transformedValue(1).must_equal true
      @transformer.transformedValue(2).must_equal true
      @transformer.transformedValue(-1).must_equal true
    end
  end

  describe 'reverse transformation' do
    it 'converts false to 0' do
      @transformer.reverseTransformedValue(false).must_equal 0
    end

    it 'converts true to 1' do
      @transformer.reverseTransformedValue(true).must_equal 1
    end
  end
end
```

*_expected output: *_

```
# Running tests:

.......

Fabulous tests in 0.009069s, 771.8602 tests/s, 882.1259 assertions/s.

7 tests, 8 assertions, 0 failures, 0 errors, 0 skips
```

**actual output:**

```
# Running tests:

....E.E..

Fabulous tests in 0.591035s, 15.2275 tests/s, 13.5356 assertions/s.

  1) Error:
test_0001_is a subclass of NSValueTransformer(AIONumberToBooleanTransformer::reverse transformation):
NoMethodError: undefined method `test_0001_is a subclass of NSValueTransformer' for #<#<Class:0x200251660>:0x2002fd8e0 ...>
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:1292:in `run'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:910:in `block'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:903:in `_run_suite'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:890:in `block'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:890:in `_run_suites'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:858:in `_run_anything'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:1051:in `run_tests'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:1038:in `block'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:1037:in `_run'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:1026:in `run'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:780:in `block'

  2) Error:
test_0001_is a subclass of NSValueTransformer(AIONumberToBooleanTransformer::transformation):
NoMethodError: undefined method `test_0001_is a subclass of NSValueTransformer' for #<#<Class:0x2002de440>:0x2002cf620 ...>
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:1292:in `run'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:910:in `block'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:903:in `_run_suite'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:890:in `block'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:890:in `_run_suites'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:858:in `_run_anything'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:1051:in `run_tests'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:1038:in `block'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:1037:in `_run'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:1026:in `run'
    /Library/Ruby/Gems/MacRuby/0.12/gems/minitest-4.2.0/lib/minitest/unit.rb:780:in `block'

9 tests, 8 assertions, 0 failures, 2 errors, 0 skips
rake aborted!
Command failed with status (1): [/Library/Frameworks/MacRuby.framework/Vers...]

Tasks: TOP => default => test
(See full trace by running task with --trace)
```

Works fine with MRI 1.9.3 (with a mocked NSValueTransformer class)... Tried minitest 4.2, 4.0, 3.0, 2.7, stdlib, all failing with MacRuby 0.12 and nightly.
