### ISSUE TITLE
must_be_kind_of throws NoMethodError: undefined method `assert_kind_of' for nil:NilClass exception in 5.0 vs. 4.6

### ISSUE THREAD

**Issue by deadprogram** [minitest/minitest#285]
When upgrading from minitest 4.6 to 5.0 I have noticed the following change in behaviour.

``
@robot.default_connection.adaptor.class.must_equal Artoo::Adaptors::Loopback # => true as expected in both 4.6 and 5.0

@robot.default_connection.adaptor.must_be_kind_of Artoo::Adaptors::Loopback # => in 4.6 was true, now throws error:

NoMethodError: undefined method `assert_kind_of' for nil:NilClass
(eval):8:in`must_be_kind_of'
``

Please let me know if I am doing something wrong, or alternatively anything I can do to further help reproduce the issue.
