### ISSUE TITLE
Stubs do not work with Ruby 1.9

### ISSUE THREAD

**Issue by djmaze** [minitest/minitest#384]
Just tried:

``` bash
$ rbenv local 2.0.0-p247
$ ruby -e "require 'minitest/mock'; Object.stub"
/home/martin/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/minitest-5.0.8/lib/minitest/mock.rb:187:in `stub': wrong number of arguments (0 for 2+) (ArgumentError)
    from -e:1:in `<main>'

$ rbenv local 1.9.3-p327-perf
$ ruby -e "require 'minitest/mock'; Object.stub"
-e:1:in `<main>': undefined method `stub' for Object:Class (NoMethodError)
```

Same with JRuby:

``` bash
$ rbenv local jruby-1.7.6

$ jruby --2.0 -e "require 'minitest/mock'; Object.stub"
ArgumentError: wrong number of arguments calling `stub` (0 for 2)

$ jruby --1.9 -e "require 'minitest/mock'; Object.stub"
NoMethodError: undefined method `stub' for Object:Class
```

Strangely it seems `require` in 1.9 does not evaluate the `Object.stub` method [defined at the bottom of mock.rb](https://github.com/seattlerb/minitest/blob/master/lib/minitest/mock.rb#L167). Does this happen for anyone else?

**Comment by redbar0n** [comment]
It seems as even ruby 2.3.1 still doesn't have a minitest version that supports stub.

```bash
› ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin13]
› ruby -e "require 'minitest/mock'; Object.stub"
~/.rvm/gems/ruby-2.3.1/gems/minitest-5.10.1/lib/minitest/mock.rb:201:in `stub': wrong number of arguments (given 0, expected 2+) (ArgumentError)
	from -e:1:in `<main>'
```
